VERTICAL_LINE = '│'
HORIZONTAL_LINE = '─'

TOP_LEFT_CORNER = '╭'
TOP_RIGHT_CORNER = '╮'

BOTTOM_LEFT_CORNER = '╰'
BOTTOM_RIGHT_CORNER = '╯'

CENTER_CONDUIT = '┼'
TOP_CENTER_CONDUIT = '┬'
BOTTOM_CENTER_CONDUIT = '┴'
LEFT_CONDUIT = '├'
RIGHT_CONDUIT = '┤'

CONDUIT_SYMBOL = 'X'

CONDUITS = [
    VERTICAL_LINE,
    HORIZONTAL_LINE,
    TOP_LEFT_CORNER,
    TOP_RIGHT_CORNER,
    BOTTOM_LEFT_CORNER,
    BOTTOM_RIGHT_CORNER,
    CENTER_CONDUIT,
    TOP_CENTER_CONDUIT,
    BOTTOM_CENTER_CONDUIT,
    LEFT_CONDUIT,
    RIGHT_CONDUIT
]

NEW_LINE = '\n'
SPACE = ' '
EMPTY = ''

RANGE_LIMITS_SEPARATOR = '-'